import {
  siCloudinary,
  siCss,
  siDocker,
  siExpress,
  siFigma,
  siGit,
  siGithub,
  siGooglecloud,
  siHtml5,
  siJavascript,
  siJenkins,
  siJest,
  siJsonwebtokens,
  siKubernetes,
  siMongodb,
  siMysql,
  siNextdotjs,
  siNginx,
  siNodedotjs,
  siPostgresql,
  siPostman,
  siReact,
  siReactquery,
  siRedis,
  siRedux,
  siRender,
  siTailwindcss,
  siTypescript,
  siVercel,
  siX,
  siZod,
  type SimpleIcon,
} from "simple-icons";

/**
 * Tech logos by slug. Keys are the slugs used for skills in the CMS (`skills.slug`).
 * Add new entries here as skills are added; unknown slugs render without a logo.
 */
export const techIcons: Record<string, SimpleIcon> = {
  react: siReact,
  nextjs: siNextdotjs,
  "node-js": siNodedotjs,
  typescript: siTypescript,
  javascript: siJavascript,
  mongodb: siMongodb,
  express: siExpress,
  "tailwind-css": siTailwindcss,
  docker: siDocker,
  kubernetes: siKubernetes,
  jenkins: siJenkins,
  git: siGit,
  github: siGithub,
  redux: siRedux,
  "react-query": siReactquery,
  postgresql: siPostgresql,
  mysql: siMysql,
  redis: siRedis,
  vercel: siVercel,
  render: siRender,
  cloudinary: siCloudinary,
  html: siHtml5,
  css: siCss,
  zod: siZod,
  jwt: siJsonwebtokens,
  "google-cloud": siGooglecloud,
  nginx: siNginx,
  postman: siPostman,
  figma: siFigma,
  jest: siJest,
  x: siX,
};
